### ISSUE TITLE
00-verify-setup fails with pip 21.3.1 or newer

### ISSUE THREAD

**Issue by Atihinen** [eficode-academy/rf-katas#20]
Workaround was to run command `pip3 install pip==21.2.4` https://github.com/jazzband/pip-tools/issues/1503#issuecomment-940409387

**Comment by asimell** [comment]
This could and should be documented in `00_getting_started.md`. Based on feedback on the training session on 8.2. installation and verification took too long, since the instructions were a bit unclear. The feedback suggested some `What if...` FAQ style troubleshooting when people have trouble with the installation.

**Comment by Atihinen** [comment]
The FAQ in 00 would really make sense since there are known things to happen.

**Comment by Tattoo** [comment]
In `setup/verify_env.py`, we do the following:

```python
from pip._internal.utils.misc import get_installed_distributions
```

This relies, as the line implies, on internals of pip which probably have changed.

Rather, we should probably do something like:

```python
try:
   import robotframework
except ImportError:
   print('"robotframework" is not correctly installed!')
```
